version: '2.2'
services:
  # Apache отключён в угоду nginx
  apache:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app:delegated
    depends_on:
      - db
    ports:
      - '8000:80'
  # Контейнер с PG
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  # Админер для простоты взаимодействия с СУБД
  adminer:
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
       - '8081:8080'
  # Фронт енд (react-app)
  frontend:
    build: ./frontend
    depends_on:
      - apache
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  # Отдельный сервер для чата на ноде (был отключен)
#  chat:
#    build: ./chat
#    depends_on:
#      - frontend
#    volumes:
#      - ./chat:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - '8082:8080'



