version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app:delegated
    ports:
      - '8000:80'
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
       - '8081:8080'
  frontend:
    build: ./frontend
    depends_on:
      - db
      - nginx
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  chat:
    build: ./chat
    volumes:
      - ./chat:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8082:8080'
  nginx:
    image: nginx:latest
    depends_on:
      - db
      - php
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./backend:/etc/nginx/app
    env_file:
      - .env


