version: '3.1'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - '4444'
  sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/root/db/
