version: '3.9'
services:
  # Apache отключён в угоду nginx
  apache:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./backend:/app:delegated
    ports:
      - '8000:80'
  # Контейнер с PG
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  # Админер для простоты взаимодействия с СУБД
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
       - '8081:8080'
  # Фронт енд (react-app)
  frontend:
    build: ./frontend
    depends_on:
      - db
      - nginx
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  # Отдельный сервер для чата на ноде
  chat:
    build: ./chat
    volumes:
      - ./chat:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8082:8080'



