<?php

namespace app\modules\admin\models;

use app\models\Country as BaseCountry;

class Country extends BaseCountry
{
    //TODO вынести в поведения (работа с файлами чи как)
    public $uploads;

    public function rules(): array
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rules[] = [['uploads'], 'file', 'extensions'=>['png', 'jpg', 'gif'], 'maxSize' => 1024*1024];
        return $rules;
    }

    public function attributeLabels()
    {
        return [
          'code' => 'Код страны (RU, EN, US...)',
          'name' => 'Название',
          'uploads' => 'Флаг',
        ];
    }

}