<?php

namespace app\modules\admin\models;

use app\models\Place as BasePlace;
use yii\db\TableSchema;

class Place extends BasePlace
{
    public function attributeLabels(): array
    {
        return [
            'name' => 'Имя',
            'address' => 'Адрес',
            'description' => 'Описание',
        ];
    }

//    public static function getTableSchema(): TableSchema
//    {
//        var_dump(parent::getTableSchema());die; // TODO: Change the autogenerated stub
//    }
}